### ISSUE TITLE
补充竖排/直排标点字形

### ISSUE THREAD

**Issue by Cl00m** [bosswnx/huiwenmincho-improved#1]
楼主你好,请问是否可以帮忙补充一些标点符号的字形?我在制作直排电子书时发现用css修改文字方向会导致直角引号,书名号等仍旧以横排方向出现,推测为缺少直排方向的字形导致,是否可以补充以下方向的标点?
︵︶︹︺︷︸︿﹀︽︾﹁﹂﹃﹄︻︼︗︘
因为我自己没有字体修改的经验,且已经有仓库作为此字体的补充,故作为issue提交,多谢

**Comment by bosswnx** [comment]
感谢反馈，我这周末找个时间弄一下，尽快更新上来

**Comment by bosswnx** [comment]
已更新，请查收。

**Comment by Cl00m** [comment]
非常感謝樓主!之前沒有及時回覆很抱歉,多謝多謝!
